apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefoljeflatefs
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefoljeflatefs/veilarbportefoljeflatefs:{{version}}
  port: 8080
  liveness:
    initialDelay: 20
    path: veilarbportefoljeflatefs/internal/isAlive
  readiness:
    path: veilarbportefoljeflatefs/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  prometheus:
    enabled: true
    path: veilarbportefoljeflatefs/internal/metrics
  ingresses:
    - https://veilarbportefoljeflatefs.nais.adeo.no
    - https://app.adeo.no/veilarbportefoljeflatefs
  vault:
    enabled: true
  envFrom:
    - configmap: pto-config
