apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefoljeflatefs
  namespace: obo
  labels:
    team: obo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.08.30_10.15-9c1569b22e37
  port: 8080
  ingresses:
    - https://veilarbportefoljeflate.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  secureLogs:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: obo-veilarbportefoljeflatefs-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: obo-unleash
          namespace: obo
        - application: veilarbfilter
          namespace: obo
        - application: endringslogg
          namespace: pto
        - application: modiacontextholder
          namespace: personoversikt
        - application: veilarbportefolje
          namespace: obo
          cluster: prod-gcp
      external:
        - host: veilarbvedtaksstotte.prod-fss-pub.nais.io
        - host: veilarbveileder.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "obo-veilarbportefoljeflatefs-prod"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no"]
            },
            "corp": {
              "policy": "cross-origin"
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://cdn.nav.no/personoversikt/internarbeidsflate-decorator-v3/prod",
              "preserveFromPath": false
            },
            {
              "fromPath": "/veilarbpersonflatefs/*",
              "toUrl": "https://veilarbpersonflate.intern.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "http://veilarbportefolje.obo",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "obo",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarbfilter",
              "toUrl": "http://veilarbfilter.obo",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbfilter",
                "namespace": "obo",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbportefoljeflatefs",
              "toUrl": "http://obo-unleash.obo",
              "preserveFromPath": false,
              "toApp": {
                "name": "obo-unleash",
                "namespace": "obo",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "http://modiacontextholder.personoversikt",
              "preserveFromPath": false,
              "toApp": {
                "name": "modiacontextholder",
                "namespace": "personoversikt",
                "cluster": "prod-gcp"
              }
            }
          ]
        }
