export enum Side {
    MIN_OVERSIKT = 'MIN_OVERSIKT',
    ENHETENS_OVERSIKT = 'ENHETENS_OVERSIKT',
    VEILEDER_OVERSIKT = 'VEILEDER_OVERSIKT',
    VEILEDER_PORTEFOLJE_OVERSIKT = 'VEILEDER_PORTEFOLJE_OVERSIKT'
}
