name: Deploy github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-gh-pages:
    name: Update GitHub pages
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build mock application
        run: npm run build:mock
      - name: Legg til 404 fil
        run: cp ./.github/pages/404.html ./dist/404.html
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # ratchet:actions/upload-pages-artifact@v5.0.0
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # ratchet:actions/deploy-pages@v5.0.0
