name: Deploy github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-gh-pages:
    name: Update GitHub pages
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build mock application
        run: npm run build:mock
      - name: Legg til 404 fil
        run: cp ./.github/pages/404.html ./dist/404.html
      - name: Update GitHub pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # ratchet:peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
